module:
  automated_cron: 0
  basic_auth: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  datetime: 0
  dblog: 0
  editor: 0
  entity_reference: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  image_raw_formatter: 0
  language: 0
  link: 0
  menu_ui: 0
  menutree_resource: 0
  node: 0
  oauth: 0
  openid_connect: 0
  options: 0
  paragraphs: 0
  path: 0
  rest: 0
  restui: 0
  search: 0
  serialization: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  wkhub_blog: 0
  wkhub_casestudies: 0
  wkhub_company: 0
  wkhub_person: 0
  wkhub_principle: 0
  wkhub_search: 0
  wkhub_services: 0
  menu_link_content: 1
  content_translation: 10
  views: 10
  wk: 1000
theme:
  classy: 0
  seven: 0
  stable: 0
  wundersimple: 0
