session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    de: de
    fi: fi
    et: et
    lv: lv
    nl: nl
    fr: fr
    sv: sv
  domains:
    en: ''
    de: ''
    fi: ''
    et: ''
    lv: ''
    nl: ''
    fr: ''
    sv: ''
selected_langcode: site_default
