resources:
  'entity:node':
    GET:
      supported_formats:
        - hal_json
      supported_auth:
        - basic_auth
        - oauth
    POST:
      supported_formats:
        - hal_json
      supported_auth:
        - basic_auth
        - oauth
    DELETE:
      supported_formats:
        - hal_json
      supported_auth:
        - basic_auth
        - oauth
    PATCH:
      supported_formats:
        - hal_json
      supported_auth:
        - basic_auth
        - oauth
  menutree:
    GET:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - cookie
  'entity:user':
    GET:
      supported_formats:
        - json
      supported_auth:
        - oauth
    PATCH:
      supported_formats:
        - json
      supported_auth:
        - oauth
link_domain: null
